continuations: fix compile warning on macOS
Fixed the following issue reported on macOS:

    ../source/../include/unifex/continuations.hpp:239:5: error: suggest
    braces around initialization of subobject [-Werror,-Wmissing-braces]
    &_ci::_default_type_index_getter,

The _continuation_handle_vtable consists of a subobject.  Add braces to
clearly indicate which members are constructed in the subobject and
which are for the object itself.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>