Fix an unused variable warning
Building with `-Werror,-Wunused-variable` produces this error:

```
libunifex/test/indexed_for_test.cpp:91:8: error: unused variable 'result'
[-Werror,-Wunused-variable]
  auto result = just(42)
       ^
1 error generated.
```

This change fixes the error by using `result` to confirm that the
calculated sum is as expected.